# docker-compose --file "dev/test-databases.docker-compose.yml" up -d

version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: queries_mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: queries_test
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - queries_mysql_data:/var/lib/mysql
  mariadb:
    image: mariadb:10.5
    container_name: queries_mariadb_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: my-secret-pw
      MARIADB_DATABASE: queries_test
    ports:
      - "3307:3306"
    volumes:
      - queries_mariadb_data:/var/lib/mysql
  postgres:
    image: postgres:15
    container_name: queries_postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: my-secret-pw
      POSTGRES_DB: queries_test
    volumes:
      - queries_postgres_data:/var/lib/postgresql/data

volumes:
  queries_mysql_data:
  queries_mariadb_data:
  queries_postgres_data: